name: Publish Docker image
on:
  push:
    branches: 
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 4 5 * *'
jobs:
  push_to_github_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v1 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: scholliyt/gamink/gamink
          tag_with_ref: true
